parameters:
  upload_directory: '%kernel.project_dir%/web/upload'
  default_cover: '%kernel.project_dir%/%upload_directory%/default.gif'

services:
  BookBundle\Service\FileUploader:
    arguments:
      $uploadDir: '%upload_directory%'