parameters:
  api_token: f3abfd8063e82d244f9315ec7daa2737
  cache_keys_to_clear: [book_list_desc]

services:
  BookBundle\Service\FileUploader:
    arguments:
      $uploadDir: '%kernel.project_dir%/web%upload_dir%'
  BookBundle\EventListener\DeleteUnusedFilesSubscriber:
    arguments:
      $uploadDir: '%kernel.project_dir%/web%upload_dir%'
    tags:
      - { name: doctrine.event_subscriber, connection: default }
  BookBundle\EventListener\ClearCacheSubscriber:
    arguments:
      $cacheKeys: '%cache_keys_to_clear%'
    tags:
      - { name: doctrine.event_subscriber, connection: default }
  BookBundle\EventListener\CheckTokenSubscriber:
    arguments:
      $token: '%api_token%'
    tags:
      - { name: kernel.event_subscriber }
  BookBundle\EventListener\ApiRequestFormatSubscriber:
    tags:
      - { name: kernel.event_subscriber }