parameters:
  upload_directory: '/upload'
  default_img_width: 200
  default_img_height: 200
  default_cache_time: 86400
  api_key: f3abfd8063e82d244f9315ec7daa2737
  cache_keys_to_clear: [list_desc]

services:
  BookBundle\Service\FileUploader:
    arguments:
      $uploadDir: '%kernel.project_dir%/web%upload_directory%'
  BookBundle\EventListener\DeleteUnusedFilesSubscriber:
    arguments:
      $uploadDir: '%kernel.project_dir%/web%upload_directory%'
    tags:
      - { name: doctrine.event_subscriber, connection: default }
  BookBundle\EventListener\ClearCacheSubscriber:
    arguments:
      $cacheKeys: '%cache_keys_to_clear%'
    tags:
      - { name: doctrine.event_subscriber, connection: default }
twig:
  globals:
    upload: '%upload_directory%'
    default_img: 'default.gif'