parameters:
  upload_directory: '/upload'

services:
  BookBundle\Service\FileUploader:
    arguments:
      $uploadDir: '%kernel.project_dir%/web%upload_directory%'
twig:
  globals:
    upload: '%upload_directory%'
    default_img: 'default.gif'