parameters:
    upload_dir: '/upload/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BookBundle\:
        resource: '../../src/BookBundle/*'
        exclude: '../../src/BookBundle/{Entity,Repository,Tests}'
twig:
  globals:
    upload_dir: '%upload_dir%'